"""
# DRPython
# Copyright (C) 2022
# Author: Lingsong HE
# Organization: Huazhong University of Science and Technology
# Contact: helingsong@hust.edu.cn
                                                       :::.                               
  .+++++++=-:   +++++++=-  -+++++++-.            .:-.  +++-                               
  .+++---=+++=  +++-:-+++= -+++-:-+++:...   .....+++:. +++-.::.     .:::.    .....::.     
  .+++.   :+++: +++-.:+++- -+++. .+++=+++.  ++++++++++.++++++++=  :+++++++-..++++++++=    
  .+++.   .+++: +++++++=:  -++++++++: :++= -++-..+++:. +++=..+++.:+++:..+++=.+++-.:+++.   
  .+++.  .=+++  +++-.=++=. -+++-::.    -++=++-   +++:  +++-  +++:-++=   ++++.+++:  +++.   
  .+++==++++=.  +++:  =+++.-+++.        =+++=    +++== +++-  +++:.=++=-=+++:.+++:  +++.   
  .------::     ---.   ----:---.        :+++.    .-==- ---:  ---.  .--=--:   ---.  ---.   
                                     .==+++:                                              
                                     .---:
                                                                                          
                            %                                                             
                            **          :==.                                              
                             *.        +@@@@@*                                            
                              +        :@@@@=                                             
                               +        *#@@=                                             
                               :=       .%@@@-                                            
                                =.      #@@@@@:                                           
                                 +     #@@@@@@+                                           
                                  +   %@*@@@@@#                                           
                                  :++@%:%@@@@#@.                                          
                                :*%#=   %@@@@=@=                 .-=-.                    
                *      .:-::=*#@#:  -   %@@@@%%*     ..:.   ..-+%@%%@@                    
              :%@#++%@@@@@@@@@@@@@+::#*%@@@@@= ::-+%@@@@@%@@@%*=:   +*                    
             *@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%@@@@@@@@@@@@@@@%*+   .%-       .            
           -%@@@@@@%@@@*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@-  +@%:   :-**=-          
          =@@@@@@+.-%:@:%@-+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@. +@@@@@@%%%###:         
        :#@@@#+=:.  : .:=- :@@@@@@@@@@@@@@@@@@@@@@@@@@@%@@@@@@@@@-  :+*##*=--**%+         
        @@@%-...           .+@@@@@@@@@@@@@@@@@@@@#@@@@@@@@@@@@@@@             *#*:        
        -=:                 -@@@@@@@%-=++##*+=-.  +#@@@@@%@@%@@@@-           =#=-         
                         #@%#@@@@%%@@-    +         .*@@@=-@@@@@@@*:                      
                       :#=.  .@@@#.:@@*   .=          :@@=  :-=+#@@@%+-                   
                     :#%.  :=#@@%*+=-:     -:          %@@=        :%@#                   
                     +@=   .  +@=           *         :@#-           =@-                  
                   *+%@#-:::.:=@*-==:.       +       =@=...:::::::-:::+@.. 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%%%%%%%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%%%%%%%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                                     
"""


#===This Frame is generated by DRPython ===============================

#Add current Python working path, remove it, if you original python is ok.
import os
import sys
import drvi.drviAppendPath as mPath
mPath.appendPythonPath()
#=========================================================================


import tkinter as tk
import tkinter.messagebox as msgbox
from tkinter import filedialog
from tkinter import *
from scipy.fftpack import fft,ifft
import matplotlib.pyplot as plt
import numpy as np
import drvi.drviDSP as dsp
import drvi.drviControlls as dr
import drvi.drviAudio as drAudio

#==Event response function of controls====
def setValueSingle(v):
 return 1

def setValueString(t):
 return 1

def setValue2DX(dx,x):
 return 1

#==Main Window=====================
win= tk.Tk()
sWOld=1920
sHOld=1080
sWidth=win.winfo_screenwidth()
sHeight=win.winfo_screenheight()
wRate=sWidth/sWOld
hRate=sHeight/sHOld
winWidth=int(1100*wRate)
winHeight=int(670*hRate)
x=(sWidth-winWidth)/2;
y=(win.winfo_screenheight()-winHeight)/2
win.geometry("%dx%d+%d+%d" %(winWidth,winHeight,x,y))
win.config(bg="#ddeeee")
win.wm_title('信号录音样例程序 -- By DRPython')

#==Layout of controls=====================
mLab1=dr.DRLabelX(win,40*wRate,32*hRate,500*wRate,40*hRate,'#004488','#ffffff','信号录音样例程序',20)
mLab2=dr.DRLabel(win,600*wRate,120*hRate,600*wRate,40*hRate,'#ddeeee','#000000','X: 0 - 0.2 秒        Y: -1 - 1')
mHBut2=dr.DRHButtonGroup(win,40*wRate,100*hRate,200*wRate,36*hRate,'#0088aa','#ffffff','运行,停止',2,0)
mRec3=drAudio.DRRecorder(win,261*wRate,100*hRate,100*wRate,36*hRate,'#000000','#ffffff',44100,10000,60)
mPlotFast4=dr.DRPlotFast(win,37*wRate,154*hRate,1000*wRate,380*hRate,'#003355','#000000','#ffffff','#006677','#ffff00',12,0,0.2,-1,1,0,0)

mHBut2.addCallBackSingle(mRec3.setValueSingle)
mRec3.addCallBack2DX(setValue2DX)
mRec3.addCallBack2DX(mPlotFast4.setValue2DX)

#==Main Loop=====================
win.mainloop()

#==End of APPp=====================

