"""
# DRPython
# Copyright (C) 2022
# Author: Lingsong HE
# Organization: Huazhong University of Science and Technology
# Contact: helingsong@hust.edu.cn
                                                       :::.                               
  .+++++++=-:   +++++++=-  -+++++++-.            .:-.  +++-                               
  .+++---=+++=  +++-:-+++= -+++-:-+++:...   .....+++:. +++-.::.     .:::.    .....::.     
  .+++.   :+++: +++-.:+++- -+++. .+++=+++.  ++++++++++.++++++++=  :+++++++-..++++++++=    
  .+++.   .+++: +++++++=:  -++++++++: :++= -++-..+++:. +++=..+++.:+++:..+++=.+++-.:+++.   
  .+++.  .=+++  +++-.=++=. -+++-::.    -++=++-   +++:  +++-  +++:-++=   ++++.+++:  +++.   
  .+++==++++=.  +++:  =+++.-+++.        =+++=    +++== +++-  +++:.=++=-=+++:.+++:  +++.   
  .------::     ---.   ----:---.        :+++.    .-==- ---:  ---.  .--=--:   ---.  ---.   
                                     .==+++:                                              
                                     .---:
                                                                                          
                            %                                                             
                            **          :==.                                              
                             *.        +@@@@@*                                            
                              +        :@@@@=                                             
                               +        *#@@=                                             
                               :=       .%@@@-                                            
                                =.      #@@@@@:                                           
                                 +     #@@@@@@+                                           
                                  +   %@*@@@@@#                                           
                                  :++@%:%@@@@#@.                                          
                                :*%#=   %@@@@=@=                 .-=-.                    
                *      .:-::=*#@#:  -   %@@@@%%*     ..:.   ..-+%@%%@@                    
              :%@#++%@@@@@@@@@@@@@+::#*%@@@@@= ::-+%@@@@@%@@@%*=:   +*                    
             *@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%@@@@@@@@@@@@@@@%*+   .%-       .            
           -%@@@@@@%@@@*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@-  +@%:   :-**=-          
          =@@@@@@+.-%:@:%@-+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@. +@@@@@@%%%###:         
        :#@@@#+=:.  : .:=- :@@@@@@@@@@@@@@@@@@@@@@@@@@@%@@@@@@@@@-  :+*##*=--**%+         
        @@@%-...           .+@@@@@@@@@@@@@@@@@@@@#@@@@@@@@@@@@@@@             *#*:        
        -=:                 -@@@@@@@%-=++##*+=-.  +#@@@@@%@@%@@@@-           =#=-         
                         #@%#@@@@%%@@-    +         .*@@@=-@@@@@@@*:                      
                       :#=.  .@@@#.:@@*   .=          :@@=  :-=+#@@@%+-                   
                     :#%.  :=#@@%*+=-:     -:          %@@=        :%@#                   
                     +@=   .  +@=           *         :@#-           =@-                  
                   *+%@#-:::.:=@*-==:.       +       =@=...:::::::-:::+@.. 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%%%%%%%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%%%%%%%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                                     
"""


#===This Frame is generated by DRPython ===============================

#Add current Python working path, remove it, if you original python is ok.
import os
import sys
import drvi.drviAppendPath as mPath
mPath.appendPythonPath()
#=========================================================================


import tkinter as tk
from tkinter import *
import tkinter.messagebox as msgbox
from tkinter import filedialog
import matplotlib.pyplot as plt
import numpy as np
from scipy import signal
import drvi.drviDSP as dsp
import drvi.drviControlls as dr
import drvi.drviSimpleAudio as sa

#==SineWave Functions for demo of 2D plot===
def sinWave(N,Fs,F,A,P):
    dt=1.0/Fs
    t=np.arange(N)*dt
    x=A*np.sin(2*np.pi*F*t+np.pi*P/180)
    return t,x

#==CallBack Function==============
def mExit():
    win.destroy()
    return 1

def mAbout():
    k=msgbox.askyesno('About','This is a APP frame exported by DRPython !')
    return 1

#==Event response function of controls====
def setValueSingle(v):
 global mFs,mLen,mA,mF,mP,tData,xData
 mF=500*1.13**v
 [tData,xData]=sinWave(mLen,mFs,mF,mA,mP)
 mPlot1.setValue2D(tData,xData)
 w=signal.windows.tukey(mLen,0.15);   
 y=xData*w
 sa.play(1,mFs,y,0) 
 return 1

#==Global Variables for demo of 2D plot and FastPlot====
mFs=44100; mLen=28000; mA=0.5; mF=500; mP=0
xData=[0 for i in range(0,mLen)]
tData=[i for i in range(0,mLen)]
[tData,xData]=sinWave(mLen,mFs,mF,mA,mP)

#==Main Window=====================
win= tk.Tk()
sWOld=1920
sHOld=1080
sWidth=win.winfo_screenwidth()
sHeight=win.winfo_screenheight()
wRate=sWidth/sWOld
hRate=sHeight/sHOld
winWidth=int(1100*wRate)
winHeight=int(670*hRate)
x=(sWidth-winWidth)/2;
y=(win.winfo_screenheight()-winHeight)/2
win.geometry("%dx%d+%d+%d" %(winWidth,winHeight,x,y))
win.config(bg="#ddeeee")
win.wm_title('Sine wave and Piano')

#==Menu==============================
menubar=tk.Menu(win)
fmenu=tk.Menu(menubar,tearoff=False)
fmenu.add_command(label="About",command=mAbout)
fmenu.add_separator()
fmenu.add_command(label="Close",command=mExit)
menubar.add_cascade(label="File",menu=fmenu)
win.config(menu=menubar)

#==Status Bar
sbar=tk.Label(win,text="Ready",bd=1,relief=tk.SUNKEN,anchor=tk.W)
sbar.pack(side=tk.BOTTOM,fill=tk.X)

#==Layout of controls=====================
mLab1=dr.DRLabelX(win,40*wRate,32*hRate,500*wRate,40*hRate,'#005577','#ffffff','Sine wave and Piano',20)
mPlot1=dr.DRPlotX(win,40*wRate,90*hRate,1000*wRate,320*hRate,'','#222222','#000000','#ffffff','#888888','#00eeff',0,0.01,-1,1,tData,xData)
mHBut2=dr.DRHButtonGroup(win,40*wRate,430*hRate,1000*wRate,40*hRate,'#000000','#ffffff','1,2,3,4,5,6,7,8,9',9,1)
mHBut2.addCallBackSingle(setValueSingle)

#==Main Loop=====================
win.mainloop()

#==End of APPp=====================

