#===This Frame is generated by DRPython ===============================
import sys
import os
import drvi.drviAppendPath as mPath
mPath.appendPythonPath()
#=================================================

import tkinter as tk
import tkinter.messagebox as msgbox
from tkinter import filedialog
import numpy as np
from scipy.fftpack import fft,ifft
import matplotlib.pyplot as plt
import numpy as np
from scipy import signal
import socket
import pickle
import drvi.drviDSP as dsp
import drvi.drviControlls as dr


#===================================================================================
def saveData(v):
    global pha,t,x1,x2,x3,x4,Fs,N,ch
    mfile=filedialog.asksaveasfile(title="Select File",defaultextension=".npz",initialfile = "Untitled.npz",filetypes=(("npz files", "*.npz"),("all files", "*.*")))
    if not mfile: return 1
    np.savez(mfile.name,ch=ch,Fs=Fs,N=N,t=t,x1=x1,x2=x2,x3=x3,x4=x4)
        

def loadData(v):
    global pha,t,x1,x2,x3,x4,Fs,N,ch
    mfile=filedialog.askopenfilename(title="Select file",defaultextension=".npz",initialfile = "Untitled.npz",filetypes=(("npz files", "*.npz"),("all files", "*.*")))
    if not mfile: return 1
    allData=np.load(mfile)
    ch=allData['ch']
    Fs=allData['Fs']
    N=allData['N']    
    x1=allData['x1']
    x2=allData['x2']
    x3=allData['x3']
    x4=allData['x4']    
    mPlot1.setValue2D(t,x1)
    mPlot2.setValue2D(t,x2)
    mPlot3.setValue2D(t,x3)
    mPlot4.setValue2D(t,x4)    

#===========================================
def renewSignal(v):
    global pha,t,x1,x2,x3,x4,Fs,N,ch
    pha=pha+15
    dt=1.0/Fs;
    t=np.arange(N)*dt
    x1=0.8*np.sin(2*np.pi*10*t+np.pi*pha/180)
    x2=0.8*signal.square(2*np.pi*10*t+np.pi*pha/180)
    x3=0.8*signal.sawtooth(2*np.pi*10*t+np.pi*pha/180,0.5)
    x4=0.3333*np.random.randn(N)     
    mPlot1.setValue2D(t,x1)
    mPlot2.setValue2D(t,x2)
    mPlot3.setValue2D(t,x3)
    mPlot4.setValue2D(t,x4)
    
#==Main Window=====================
win= tk.Tk()
sWOld=1920
sHOld=1080
sWidth=win.winfo_screenwidth()
sHeight=win.winfo_screenheight()
wRate=sWidth/sWOld
hRate=sHeight/sHOld
winWidth=int(1100*wRate)
winHeight=int(670*hRate)
x=(sWidth-winWidth)/2;
y=(win.winfo_screenheight()-winHeight)/2
win.geometry("%dx%d+%d+%d" %(winWidth,winHeight,x,y))
win.config(bg="#ddeeee")
win.wm_title('Save and Load Signal')

#==Layout of controls=====================
mTimer1=dr.DRTimer(win,200*wRate,30*hRate,120*wRate,36*hRate,'#000000','#ffffff',100)
mLab1=dr.DRLabelX(win,20*wRate,30*hRate,400*wRate,40*hRate,'#003355','#ffffff','Save and Load Signal',20)
mPlot1=dr.DRPlotX(win,20*wRate,80*hRate,520*wRate,280*hRate,'','#003355','#000000','#ffffff','#00eeff','#ffff00',0,0,-1,1,0,0)
mPlot2=dr.DRPlotX(win,20*wRate,350*hRate,520*wRate,280*hRate,'','#003355','#000000','#ffffff','#00eeff','#ffff00',0,0,-1,1,0,0)
mPlot3=dr.DRPlotX(win,540*wRate,80*hRate,520*wRate,280*hRate,'','#003355','#000000','#ffffff','#00eeff','#ffff00',0,0,-1,1,0,0)
mPlot4=dr.DRPlotX(win,540*wRate,350*hRate,520*wRate,280*hRate,'','#003355','#000000','#ffffff','#00eeff','#ffff00',0,0,-1,1,0,0)

mBut1=dr.DRButton(win,940*wRate,40*hRate,120*wRate,36*hRate,'#114433','#ffffff','RefreshSignal',101)
mBut1.addCallBackSingle(renewSignal)

mBut2=dr.DRButton(win,810*wRate,40*hRate,120*wRate,36*hRate,'#554433','#ffffff','SaveSignal',101)
mBut2.addCallBackSingle(saveData)

mBut3=dr.DRButton(win,680*wRate,40*hRate,120*wRate,36*hRate,'#114477','#ffffff','LoadSignal',101)
mBut3.addCallBackSingle(loadData)

#=================================================================
pha=0
t=0
x1=0
x2=0
x3=0
x4=0
ch=4
Fs=500;
N=1024

#==Main Loop=====================
win.mainloop()

#==End of APPp=====================

