#===This Frame is generated by DRPython ===============================
import sys
import os
import drvi.drviAppendPath as mPath
mPath.appendPythonPath()
#=================================================

import tkinter as tk
import tkinter.messagebox as msgbox
from tkinter import filedialog
import numpy as np
from scipy.fftpack import fft,ifft
import matplotlib.pyplot as plt
import numpy as np
from scipy import signal
import drvi.drviDSP as dsp
import drvi.drviControlls as dr
import drvi.drviSimpleAudio as sa

#=========================================
def setValue1(v):
 Fs=44100;
 dt=1.0/Fs;
 N=40000;
 mF=500*1.13**v
 tData=np.arange(N)*dt
 xData=0.8*np.sin(2*np.pi*mF*tData)
 mPlotWave.setValue2D(tData,xData)
 [mFre,mAmp]=dsp.AmpSpetrumX(N,Fs,xData)
 mPlotAmp.setValue2D(mFre,mAmp)
 mDigital1.setValueSingle(mF)

def setValue(v):
 Fs=44100;
 dt=1.0/Fs;
 N=40000;
 mF=500*1.13**v
 tData=np.arange(N)*dt
 xData=0.8*np.sin(2*np.pi*mF*tData)
 mPlotWave.setValue2DFast(tData,xData)
 [mFre,mAmp]=dsp.AmpSpetrumX(N,Fs,xData)
 mPlotAmp.setValue2DFast(mFre,mAmp)
 mDigital1.setValueSingle(mF) 
 w=signal.windows.tukey(N,0.1);   
 y=xData*w
 sa.play(1,Fs,y,0)

def winResize(event):
    w=win.winfo_width()
    h=win.winfo_height()
    mWidSize.resize(w,h)
    
#==Main Window=====================
win= tk.Tk()
winWidthCur=1100
winHeightCur=670
win.geometry("%dx%d" %(winWidthCur,winHeightCur))
win.config(bg="#ddeeee")
win.bind('<Configure>',winResize) 
mWidSize=dr.DRResize(winWidthCur,winHeightCur)
win.wm_title('DRVI-正弦波纯音信号波形和频谱')

#==Layout of controls=====================
mLab1=dr.DRLabel(win,20,30,400,40,'#003355','#ffffff','正弦波纯音信号波形和频谱',20)
mPlotWave=dr.DRPlot(win,20,80,1000,245,'','#003355','#000000','#ffffff','#00eeff','#ffff00',0,0.01,-1,1,0,0)
mPlotAmp=dr.DRPlot(win,20,330,1000,245,'','#003355','#000000','#ffffff','#00eeff','#ffff00',0,2500,0,1,0,0)
mHBut2=dr.DRHButtonGroup(win,20,580,1000,50,'#000000','#ffffff','1,2,3,4,5,6,7,8,9',12,0)
mDigital1=dr.DRDigital(win,920,40,100,36,'#000000','#00ffaa',0,0,22)
#==DataStream Binding=====================
mHBut2.addCallBackSingle(setValue)


#===============================
mWidSize.addDRWidget(mLab1)
mWidSize.addDRWidget(mPlotWave)
mWidSize.addDRWidget(mPlotAmp)
mWidSize.addDRWidget(mHBut2)
mWidSize.addDRWidget(mDigital1)

#==Main Loop=====================
win.mainloop()

#==End of APPp=====================

