#===This Frame is generated by DRPython ===============================
import sys
import os
import drvi.drviAppendPath as mPath
mPath.appendPythonPath()
#=================================================

import tkinter as tk
import numpy as np
from scipy.fftpack import fft,ifft
import matplotlib.pyplot as plt
import numpy as np
import drvi.drviDSP as dsp
import drvi.drviControlls as dr
import drvi.drviSimpleAudio as ply
import warnings
warnings.filterwarnings('ignore')
#=========================================
def setValue2DX(dx,x):
 mPlot.setValue2DX(dx,x)
 mFs=1/dx
 mLen=len(x)
 [mFre,mAmp]=dsp.AmpSpetrum(mLen,mFs,x)
 df=mFs/mLen
 mPlot1.setValue2DX(df,mAmp)

#==GUI动态调整==========================================
def winResize(event):
    w=win.winfo_width()
    h=win.winfo_height()
    mWidSize.resize(w,h)
        
#==Main Window=====================
win= tk.Tk()
win.geometry("1100x670")
win.config(bg="#ddeeee")
win.wm_title('DRVI-WAV文件放音样例程序')
winWidthCur=1100
winHeightCur=670
win.bind('<Configure>',winResize) 
#==Layout of controls===============
mLab1=dr.DRLabel(win,20,30,400,40,'#445577','#ffffff','WAV文件放音样例程序',20)
mHBut2=dr.DRHButtonGroup(win,460,30,200,36,'#006688','#ffffff','播放,停止,文件',12,0)
mEntry1=dr.DREntry(win,665,30,270,36,'#000000','#ffff00','',10)
mPlay=ply.DRPlay(win,940,30,100,36,'#002244','#ffffff',11)
mPlot=dr.DRPlotFast(win,30,90,1000,280,'#003355','#000000','#ffffff','#006677','#ffff00',12,0,0.2,-1,1,0,0)
mPlot1=dr.DRPlotFast(win,30,365,1000,280,'#003355','#000000','#ffffff','#006677','#ffff00',12,0,6000,0,0.25,0,0)
#=================================
mHBut2.addCallBackSingle(mPlay.setValueSingle)
mPlay.addCallBack2DX(setValue2DX)
mPlay.addCallBackStrFile(mEntry1.setValueString)
#===============================
mWidSize=dr.DRResize(1100,670)
mWidSize.addDRWidget(mLab1)
mWidSize.addDRWidget(mHBut2)
mWidSize.addDRWidget(mEntry1)
mWidSize.addDRWidget(mPlay)
mWidSize.addDRWidget(mPlot)
mWidSize.addDRWidget(mPlot1)
#==============================
initFile=mPath.getDRVIPath()+'\\dataset\\voice1.mp3'
mEntry1.setValueString(initFile)
mPlay.setValueString(initFile)
#==Main Loop===================
win.mainloop()
#==End of APPp=====================

