#===This Frame is generated by DRPython ===============================
import sys
import os
import drvi.drviAppendPath as mPath
mPath.appendPythonPath()
#=================================================

import tkinter as tk
import tkinter.messagebox as msgbox
from tkinter import filedialog
import numpy as np
from scipy.fftpack import fft,ifft
import numpy as np
import drvi.drviDSP as dsp
import drvi.drviControlls as dr

#=========================================
def setValue2D(t,x):
 Fs=1/(t[1]-t[0]);
 N=len(x)
 mPlotWave.setValue2DFast(t,x)
 [mFre,mAmp]=dsp.AmpSpetrumX(N,Fs,x)
 mPlotAmp.setValue2DFast(mFre,mAmp)
 
def winResize(event):
    w=win.winfo_width()
    h=win.winfo_height()
    mWidSize.resize(w,h)
    
#==Main Window=====================
win= tk.Tk()
winWidthCur=1100
winHeightCur=670
win.geometry("%dx%d" %(winWidthCur,winHeightCur))
win.config(bg="#ddeeee")
win.bind('<Configure>',winResize) 
mWidSize=dr.DRResize(winWidthCur,winHeightCur)
win.wm_title('DRVI-典型信号波形和频谱')

#==Layout of controls=====================
mLab1=dr.DRLabel(win,20,30,400,40,'#003355','#ffffff','典型信号波形和频谱',20)
mPlotWave=dr.DRPlot(win,20,80,900,280,'','#003355','#000000','#ffffff','#00eeff','#ffff00',0,0.05,-1,1,0,0)
mPlotAmp=dr.DRPlot(win,20,365,900,280,'','#003355','#000000','#ffffff','#00eeff','#ffff00',0,5000,0,1,0,0)
mVButType=dr.DRRadioBut(win,940,80,120,140,'#003355','#005577',"#ffff00",'正弦波,方波,三角波,白噪声',12,0,0)
mKnobA=dr.DRKnob(win,930,280,130,130,'#004466','#222222','#aaaaaa','0,1',0,1,0.5,11)
mKnobFre=dr.DRKnob(win,930,400,130,130,'#004466','#222222','#aaaaaa','1,1000',1,1000,50,11)
mSwitch1=dr.DRSwitch(win,960,600,80,36,'#004466','#aaddee')
mType=0; Fs=44100; N=4096; A=0.6; Fre=100; Pha=0
mSignal=dsp.DRGenerator(mType,Fs,N,A,Fre,Pha)

#==DataStream Binding=====================
mSwitch1.addCallBackSingle(mSignal.setValueSingle)
mSignal.addCallBack2D(setValue2D)
mVButType.addCallBackSingle(mSignal.setVSType)
mKnobA.addCallBackSingle(mSignal.setVSAmp)
mKnobFre.addCallBackSingle(mSignal.setVSFre)
mSignal.setVSPha(0)

#===============================
mWidSize.addDRWidget(mLab1)
mWidSize.addDRWidget(mPlotWave)
mWidSize.addDRWidget(mPlotAmp)
mWidSize.addDRWidget(mVButType)
mWidSize.addDRWidget(mKnobA)
mWidSize.addDRWidget(mKnobFre)
mWidSize.addDRWidget(mSwitch1)
 
#==Main Loop=====================
win.mainloop()

#==End of APPp=====================

