#===This Frame is generated by DRPython ===============================
import sys
import os
import drvi.drviAppendPath as mPath
mPath.appendPythonPath()
#=================================================

import tkinter as tk
import tkinter.messagebox as msgbox
from tkinter import filedialog
import numpy as np
from scipy.fftpack import fft,ifft
import matplotlib.pyplot as plt
import numpy as np
import drvi.drviDSP as dsp
import drvi.drviControlls as dr
 
#==CallBack Function==============
def myWorking(v):
 Fs1=1000; dt1=1.0/Fs1; N1=int(1/dt1) 
 t1=np.arange(N1)*dt1
 x1=0.8*np.sin(2*np.pi*v*t1)
 mPlotWave1.setValue2D(t1,x1)
 Fs2=100; dt2=1.0/Fs2; N2=int(1/dt2) 
 t2=np.arange(N2)*dt2
 x2=0.8*np.sin(2*np.pi*v*t2)
 mPlotWave2.setValue2D(t2,x2)
 if v<Fs2/2: mDigital2.setValueSingle(v)
 if v>=Fs2/2: mDigital2.setValueSingle(Fs2-v)
 Fs2=100; dt2=1.0/Fs2; N2=2048
 t2=np.arange(N2)*dt2
 x2=0.8*np.sin(2*np.pi*v*t2)
 [mFre,mAmp]=dsp.AmpSpetrumX(N2,Fs2,x2)
 mPlotAmp.setValue2D(mFre,mAmp) 
 return 1

#==Main Window=====================
win= tk.Tk()
sWOld=1920
sHOld=1080
sWidth=win.winfo_screenwidth()
sHeight=win.winfo_screenheight()
wRate=sWidth/sWOld
hRate=sHeight/sHOld
winWidth=int(1100*wRate)
winHeight=int(670*hRate)
x=(sWidth-winWidth)/2;
y=(win.winfo_screenheight()-winHeight)/2
win.geometry("%dx%d+%d+%d" %(winWidth,winHeight,x,y))
win.config(bg="#ddeeee")
win.wm_title('Sampling and Aliasing')

#==Layout of controls=====================
mInfo1=dr.DRInfo(win,540*wRate,25*hRate,40*wRate,40*hRate,'#00bbbb','#000000','#ffffff','DRPython.pdf')
dr.DRLabelX(win,20*wRate,25*hRate,500*wRate,40*hRate,'#440000','#ffffff','Sampling and Aliasing',20)
mPlotWave1=dr.DRPlotX(win,20*wRate,70*hRate,900*wRate,200*hRate,'','#113344','#000000','#ffffff','#00eeff','#ffff00',0,1,-1,1,0,0)
mPlotWave2=dr.DRPlotX(win,20*wRate,255*hRate,900*wRate,200*hRate,'','#113344','#000000','#ffffff','#00eeff','#ffff00',0,1,-1,1,0,0)
mPlotAmp=dr.DRPlotX(win,20*wRate,440*hRate,900*wRate,200*hRate,'','#113344','#000000','#ffffff','#00eeff','#ffff00',0,50,0,1,0,0)
dr.DRLabelX(win,800*wRate,70*hRate,120*wRate,30*hRate,'#663300','#ffffff','Fs = 1000Hz',12)
dr.DRLabelX(win,800*wRate,260*hRate,120*wRate,30*hRate,'#663300','#ffffff','Fs = 100Hz',12)

dr.DRLabelX(win,930*wRate,80*hRate,160*wRate,30*hRate,'#ddeeee','#000000','Signal Frequency:',12)
mKnobA=dr.DRGKnob(win,930*wRate,120*hRate,150*wRate,150*hRate,'#001122','#226688','#222222','#aaaaaa','0,100',0,100,5)
mSpin1=dr.DRSpinBox(win,940*wRate,275*hRate,140*wRate,26*hRate,'#ffffff','#000000',5,1,0,100)
mDigital1=dr.DRDigital(win,940*wRate,320*hRate,140*wRate,40*hRate,'#000000','#00ffaa',5,2,22)
dr.DRLabelX(win,930*wRate,460*hRate,160*wRate,30*hRate,'#ddeeee','#000000','Aliasing Frequency',12)
mDigital2=dr.DRDigital(win,940*wRate,500*hRate,140*wRate,40*hRate,'#000000','#00ffaa',5,2,22)

#==DataStream Binding=====================
mKnobA.addCallBackSingle(mDigital1.setValueSingle)
mKnobA.addCallBackSingle(mSpin1.setValueSingle)
mKnobA.addCallBackSingle(myWorking)
mSpin1.addCallBackSingle(mDigital1.setValueSingle)
mSpin1.addCallBackSingle(mKnobA.setValueSingle)
mSpin1.addCallBackSingle(myWorking)

myWorking(5)

#==Main Loop=====================
win.mainloop()

#==End of APPp=====================

