#===This Frame is generated by DRPython ===============================
import sys
import os
import drvi.drviAppendPath as mPath
mPath.appendPythonPath()
#=================================================

import tkinter as tk
import tkinter.messagebox as msgbox
from tkinter import filedialog
import numpy as np
from scipy.fftpack import fft,ifft
import matplotlib.pyplot as plt
import numpy as np
import drvi.drviDSP as dsp
import drvi.drviControlls as dr
import drvi.drviSimpleAudio as sa
 
#==CallBack Function==============
def myWorking(v):
 global Fs,N,tData,xData,xData1
 if v==0: xData1=np.round(128*xData)/128
 if v==1: xData1=np.round(64*xData)/64
 if v==2: xData1=np.round(32*xData)/32
 if v==3: xData1=np.round(16*xData)/16
 if v==4: xData1=np.round(8*xData)/8
 if v==5: xData1=np.round(4*xData)/4
 if v==6: xData1=0.8*np.round(2*xData)/2
 if v==7: xData1=0.8*np.round(xData) 
 mPlotWave2.setValue2D(tData,xData1)
 return 1

def myPlay(v):
 global Fs,N,tData,xData
 sa.play(1,Fs,xData1,0) 
 return 1

#=====================================


#==Main Window=====================
win= tk.Tk()
sWOld=1920
sHOld=1080
sWidth=win.winfo_screenwidth()
sHeight=win.winfo_screenheight()
wRate=sWidth/sWOld
hRate=sHeight/sHOld
winWidth=int(1100*wRate)
winHeight=int(670*hRate)
x=(sWidth-winWidth)/2;
y=(win.winfo_screenheight()-winHeight)/2
win.geometry("%dx%d+%d+%d" %(winWidth,winHeight,x,y))
win.config(bg="#ddeeee")
win.wm_title('Quantization noise in Analog to Digital Convert')

#==Layout of controls=====================
mInfo1=dr.DRInfo(win,420*wRate,25*hRate,40*wRate,40*hRate,'#00bbbb','#000000','#ffffff','DRPython.pdf')
dr.DRLabelX(win,20*wRate,25*hRate,380*wRate,40*hRate,'#440000','#ffffff','Quantization Noise in ADC',18)
mPlotWave1=dr.DRPlotX(win,20*wRate,90*hRate,1000*wRate,280*hRate,'','#002f5e','#000000','#ffffff','#00eeff','#ffff00',0,0.01,-1,1,0,0)
mPlotWave2=dr.DRPlotX(win,20*wRate,355*hRate,1000*wRate,280*hRate,'','#002f5e','#000000','#ffffff','#00eeff','#ffff00',0,0.01,-1,1,0,0)
mBut=dr.DRGButton(win,930*wRate,50*hRate,90*wRate,36*hRate,'#003300','#00aa00','#ffffff',12,'Playing',12,101)
mHBut1=dr.DRHButtonGroup(win,510*wRate,50*hRate,400*wRate,36*hRate,'#114433','#ffffff','256,128,64,32,16,8,4,2',8,0)

mHBut1.addCallBackSingle(myWorking)
mBut.addCallBackSingle(myPlay)
#=======================================
Fs=44100;
dt=1.0/Fs;
N=40000;
tData=np.arange(N)*dt
xData=0.8*np.sin(2*np.pi*800*tData)
xData1=xData
mPlotWave1.setValue2D(tData,xData)
myWorking(0)

#==Main Loop=====================
win.mainloop()

     
#==End of APPp=====================

