#===This Frame is generated by DRPython ===============================
import sys
import os
import drvi.drviAppendPath as mPath
mPath.appendPythonPath()
#=================================================

import tkinter as tk
import tkinter.messagebox as msgbox
from tkinter import filedialog
import numpy as np
from scipy.fftpack import fft,ifft
import matplotlib.pyplot as plt
import numpy as np
import drvi.drviDSP as dsp
import drvi.drviControlls as dr
import drvi.drviSimpleAudio as sa
 
#==CallBack Function==============
def myWorking(v):
 Fs=44100;
 dt=1.0/Fs;
 N=500;
 tData=np.arange(N)*dt
 pa=10*mTimer1.getValueSingle()/250
 pha=mPha.get()
 rate=mType.get()+1
 xData=0.8*np.sin(2*np.pi*800*tData+(pa+pha)*np.pi/180)
 xData1=0.8*np.cos(2*np.pi*800*rate*tData+pa*np.pi/180)
 mPlotWave1.setValue2D(tData,xData)
 mPlotWave2.setValue2D(tData,xData1)
 mPlotOrbit.setValue2D(xData,xData1)
 return 1

#==Main Window=====================
win= tk.Tk()
sWOld=1920
sHOld=1080
sWidth=win.winfo_screenwidth()
sHeight=win.winfo_screenheight()
wRate=sWidth/sWOld
hRate=sHeight/sHOld
winWidth=int(1100*wRate)
winHeight=int(670*hRate)
x=(sWidth-winWidth)/2;
y=(win.winfo_screenheight()-winHeight)/2
win.geometry("%dx%d+%d+%d" %(winWidth,winHeight,x,y))
win.config(bg="#ddeeee")
win.wm_title('Lissajous Figures')


#==Variable for binding=======================================
mPha=tk.DoubleVar()
mPha.set(0)
mType=tk.DoubleVar()
mType.set(0)
mPha=tk.DoubleVar()
mPha.set(0)

#==Layout of controls=====================
mTimer1=dr.DRTimer(win,300*wRate,30*hRate,80*wRate,32*hRate,'#000000','#ffffff',250)
dr.DRLabelX(win,20*wRate,25*hRate,380*wRate,40*hRate,'#440000','#ffffff','Lissajous Figures',20)
mPlotWave1=dr.DRPlotX(win,20*wRate,90*hRate,480*wRate,280*hRate,'','#002f5e','#000000','#ffffff','#00eeff','#ffff00',0,0.01,-1,1,0,0)
mPlotWave2=dr.DRPlotX(win,20*wRate,360*hRate,480*wRate,280*hRate,'','#002f5e','#000000','#ffffff','#00eeff','#ffff00',0,0.01,-1,1,0,0)
mPlotOrbit=dr.DRPlotX(win,500*wRate,90*hRate,560*wRate,550*hRate,'','#002f5e','#000000','#ffffff','#00eeff','#ffff00',-1,1,-1,1,0,0)
mSwitch1=dr.DRSwitch(win,980*wRate,50*hRate,65*wRate,32*hRate,'#004466','#aaddee')
mHBut1=dr.DRHButtonGroup(win,500*wRate,52*hRate,160*wRate,30*hRate,'#004466','#ffffff','1,2,3,4',4,0)
mHSlider1=dr.DRHSlider(win,670*wRate,52*hRate,280*wRate,30*hRate,'#444444','#004466','#008822',8,20,0,180,0)

#==Binding==================================================
mSwitch1.addCallBackSingle(mTimer1.setValueSingle)
mTimer1.addCallBackSingle(myWorking)
mHBut1.addCallBackSingle(myWorking)
mHSlider1.addCallBackSingle(myWorking)
mHBut1.bindVariable(mType)
mHSlider1.bindVariable(mPha)

myWorking(0)
    
#==Main Loop=====================
win.mainloop()

#==End of APPp=====================

