#===This Frame is generated by DRPython ===============================
import sys
import os
import drvi.drviAppendPath as mPath
mPath.appendPythonPath()
#=================================================

import tkinter as tk
import tkinter.messagebox as msgbox
from tkinter import filedialog
import numpy as np
from scipy.fftpack import fft,ifft
import matplotlib.pyplot as plt
import numpy as np
from scipy import signal
import drvi.drviDSP as dsp
import drvi.drviControlls as dr
import drvi.drviSimpleAudio as sa

#=========================================

def setValue(v):
 Fs=44100;
 dt=1.0/Fs;
 N=40000;
 if v==1: f1=697;f2=1209
 if v==2: f1=697;f2=1336
 if v==3: f1=697;f2=1477
 if v==4: f1=770;f2=1209
 if v==5: f1=770;f2=1336
 if v==6: f1=770;f2=1477
 if v==7: f1=852;f2=1209
 if v==8: f1=852;f2=1366
 if v==9: f1=852;f2=1477
 if v==10: f1=941;f2=1209
 if v==11: f1=941;f2=1336
 if v==12: f1=941;f2=1477
 tData=np.arange(N)*dt
 x1=0.8*np.sin(2*np.pi*f1*tData)
 x2=0.8*np.sin(2*np.pi*f2*tData)
 xData=x1+x2
 mPlotWave.setValue2D(tData,xData)
 [mFre,mAmp]=dsp.AmpSpetrumX(N,Fs,xData)
 mPlotAmp.setValue2D(mFre,mAmp)
 sa.play(1,Fs,xData,0)
 s=str(f1)+' + '+str(f2)
 mTxt.setValueString(s)

def getData(v):
 Fs=44100;
 dt=1.0/Fs;
 N=40000;
 if v==1: f1=697;f2=1209
 if v==2: f1=697;f2=1336
 if v==3: f1=697;f2=1477
 if v==4: f1=770;f2=1209
 if v==5: f1=770;f2=1336
 if v==6: f1=770;f2=1477
 if v==7: f1=852;f2=1209
 if v==8: f1=852;f2=1366
 if v==9: f1=852;f2=1477
 if v==10: f1=941;f2=1209
 if v==11: f1=941;f2=1336
 if v==12: f1=941;f2=1477
 tData=np.arange(N)*dt
 x1=0.8*np.sin(2*np.pi*f1*tData)
 x2=0.8*np.sin(2*np.pi*f2*tData)
 xData=x1+x2
 mPlotWave.setValue2D(tData,xData)
 [mFre,mAmp]=dsp.AmpSpetrumX(N,Fs,xData)
 mPlotAmp.setValue2D(mFre,mAmp)
 s=str(f1)+' + '+str(f2)
 mTxt.setValueString(s)

  
#==Main Window=====================
win= tk.Tk()
sWOld=1920
sHOld=1080
sWidth=win.winfo_screenwidth()
sHeight=win.winfo_screenheight()
wRate=sWidth/sWOld
hRate=sHeight/sHOld
winWidth=int(1100*wRate)
winHeight=int(670*hRate)
x=(sWidth-winWidth)/2;
y=(win.winfo_screenheight()-winHeight)/2
win.geometry("%dx%d+%d+%d" %(winWidth,winHeight,x,y))
win.config(bg="#ddeeee")
win.wm_title('Sine Wave and DTMF')

#==Layout of controls=====================
mInfo1=dr.DRInfo(win,440*wRate,30*hRate,40*wRate,40*hRate,'#00bbbb','#000000','#ffffff','DRPython.pdf')
mLab1=dr.DRLabelX(win,20*wRate,30*hRate,400*wRate,40*hRate,'#003355','#ffffff','Sine Wave and DTMF',20)
mPlotWave=dr.DRPlotX(win,20*wRate,80*hRate,840*wRate,260*hRate,'','#003355','#000000','#ffffff','#00eeff','#ffff00',0,0.01,-2,2,0,0)
mPlotAmp=dr.DRPlotX(win,20*wRate,330*hRate,840*wRate,260*hRate,'','#003355','#000000','#ffffff','#00eeff','#ffff00',0,2500,0,1,0,0)
mHBut2=dr.DRHButtonGroup(win,880*wRate,200*hRate,180*wRate,60*hRate,'#000000','#ffffff','1,2,3',3,1)
mHBut3=dr.DRHButtonGroup(win,880*wRate,260*hRate,180*wRate,60*hRate,'#000000','#ffffff','4,5,6',3,4)
mHBut4=dr.DRHButtonGroup(win,880*wRate,320*hRate,180*wRate,60*hRate,'#000000','#ffffff','7,8,9',3,7)
mHBut5=dr.DRHButtonGroup(win,880*wRate,380*hRate,180*wRate,60*hRate,'#000000','#ffffff','.,0,#',3,10)
mTxt=dr.DRLabelX(win,880*wRate,160*hRate,180*wRate,40*hRate,'#000000','#00ffaa','0',20)

#==DataStream Binding=====================
mHBut2.addCallBackSingle(setValue)
mHBut3.addCallBackSingle(setValue)
mHBut4.addCallBackSingle(setValue)
mHBut5.addCallBackSingle(setValue)

getData(1)

#==Main Loop=====================
win.mainloop()

#==End of APPp=====================

