#===This Frame is generated by DRPython ===============================
import sys
import os
import drvi.drviAppendPath as mPath
mPath.appendPythonPath()
#=================================================

import tkinter as tk
import tkinter.messagebox as msgbox
from tkinter import filedialog
import numpy as np
from scipy.fftpack import fft,ifft
import matplotlib.pyplot as plt
import numpy as np
import drvi.drviDSP as dsp
import drvi.drviControlls as dr

#=========================================
def setValue(v):
 Fs=32768;
 dt=1.0/Fs;
 N=32768;
 F=70
 t=np.arange(N)*dt
 x=0*t 
 if v==0: M=1
 if v==1: M=2
 if v==2: M=3
 if v==3: M=4
 if v==4: M=5
 if v==5: M=6
 if v==6: M=7
 if v==7: M=8
 if v==8: M=9
 if v==9: M=10
 if v==10: M=20
 if v==11: M=40
 for i in range(M):
     k=1+2*i; a=1/k
     x=x+a*0.8*np.sin(2*np.pi*k*F*t)
 mPlotWave.setValue2D(t,x)
 [mFre,mAmp]=dsp.AmpSpetrum(N,Fs,x)
 mPlotAmp.setValue2D(mFre,mAmp)
  
 
#==Main Window=====================
win= tk.Tk()
sWOld=1920
sHOld=1080
sWidth=win.winfo_screenwidth()
sHeight=win.winfo_screenheight()
wRate=sWidth/sWOld
hRate=sHeight/sHOld
winWidth=int(1100*wRate)
winHeight=int(670*hRate)
x=(sWidth-winWidth)/2;
y=(win.winfo_screenheight()-winHeight)/2
win.geometry("%dx%d+%d+%d" %(winWidth,winHeight,x,y))
win.config(bg="#ddeeee")
win.wm_title('Fourier Series and Gibbs Phenomenon')

#==Layout of controls=====================
mLab1=dr.DRLabelX(win,20*wRate,30*hRate,600*wRate,40*hRate,'#003355','#ffffff','Fourier Series and Gibbs Phenomenon',20)
mPlotWave=dr.DRPlotX(win,20*wRate,80*hRate,900*wRate,280*hRate,'','#003355','#000000','#ffffff','#00eeff','#ffff00',0,0.05,-1,1,0,0)
mPlotAmp=dr.DRPlotX(win,20*wRate,350*hRate,900*wRate,280*hRate,'','#003355','#000000','#ffffff','#00eeff','#ffff00',0,4000,0,1,0,0)
mVButType=dr.DRRadioButX(win,930*wRate,80*hRate,120*wRate,550*hRate,'#004466','#000000','#ffffff','#00ccff','#eeee44','1,1+3,1+3+5,1+3+5+7,1+3+...+9,1+3+...+11,1+3+...+13,1+3+...+15,1+3+...+17,1+3+...+19,1+3+...+41,1+3+...+81',11,12,0)

#===================================
mVButType.addCallBackSingle(setValue)
setValue(0)
#==Main Loop=====================
win.mainloop()

#==End of APPp=====================

