#===This Frame is generated by DRPython ===============================
import sys
import os
import drvi.drviAppendPath as mPath
mPath.appendPythonPath()
#=================================================

import tkinter as tk
import numpy as np
from scipy.fftpack import fft,ifft
import matplotlib.pyplot as plt
import numpy as np
import drvi.drviDSP as dsp
import drvi.drviControlls as dr
import drvi.drviSimpleAudio as ply
import tkinter as tk
import tkinter.ttk as ttk
from tkinter import *
import matplotlib.pyplot as plt
from pylab import mpl
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib import cm
import numpy as np
import math


#=========================================
def setValue2DX(dx,x):
 CH=x.ndim
 if CH==2:x=x[:,0] #立体声，取一通道数据
 mPlotF.setValue2DX(dx,x)
 mFs=1/dx
 mLen=len(x)
 f,s=dsp.oct31SpecDB(mFs,x)
 M=len(s)
 xBar=np.arange(M)
 mPlotBar1.setValue2D(xBar,s)
 
        
#==Main Window=====================
win= tk.Tk()
sWOld=1920
sHOld=1080
sWidth=win.winfo_screenwidth()
sHeight=win.winfo_screenheight()
wRate=sWidth/sWOld
hRate=sHeight/sHOld
winWidth=int(1100*wRate)
winHeight=int(670*hRate)
x=(sWidth-winWidth)/2;
y=(win.winfo_screenheight()-winHeight)/2
win.geometry("%dx%d+%d+%d" %(winWidth,winHeight,x,y))
win.config(bg="#ddeeee")
win.wm_title('Waveform and Octave of WAV File')

#==Layout of controls=====================
mLab1=dr.DRLabelX(win,20*wRate,30*hRate,600*wRate,40*hRate,'#445577','#ffffff','Waveform and Octave of WAV File',20)
mHBut2=dr.DRHButtonGroup(win,690*wRate,30*hRate,200*wRate,36*hRate,'#006688','#ffffff','Play,Stop',2,0)
mPlay=ply.DRPlay(win,900*wRate,30*hRate,120*wRate,36*hRate,'#002244','#ffffff')
mPlotF=dr.DRPlotFast(win,20*wRate,80*hRate,1000*wRate,270*hRate,'#003355','#000000','#ffffff','#006677','#ffff00',12,0,0.2,-1,1,0,0)
mPlotBar1=dr.DRPlotBarX(win,20*wRate,340*hRate,1000*wRate,270*hRate,'','#003355','#000000','#ffffff','#00eeff','#00ff44',0,32,20,100,0,0)
dr.DRLabelX(win,56*wRate,577*hRate,960*wRate,20*hRate,'#003355','#ffffff','',12)
L1=dr.DRLabelX(win,60*wRate,575*hRate,60*wRate,30*hRate,'#003355','#ffffff','10Hz',10)
L1=dr.DRLabelX(win,940*wRate,575*hRate,60*wRate,30*hRate,'#003355','#ffffff','20KHz',10)

#====================================
mHBut2.addCallBackSingle(mPlay.setValueSingle)
mPlay.addCallBack2DX(setValue2DX)


#==Main Loop=====================
win.mainloop()

#==End of APPp=====================

