#===This Frame is generated by DRPython ===============================
import sys
import os
import drvi.drviAppendPath as mPath
mPath.appendPythonPath()
#=================================================

import tkinter as tk
import tkinter.messagebox as msgbox
from tkinter import filedialog
from tkinter import *
from scipy.fftpack import fft,ifft
import matplotlib.pyplot as plt
from pylab import mpl
from matplotlib import cm
import numpy as np
import tkinter as tk
import tkinter.ttk as ttk
from tkinter import *
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib import cm
import numpy as np
import math
import drvi.drviDSP as dsp
import drvi.drviControlls as dr
import drvi.drviAudio as drAudio


#==Event response function of controls====
def setValue2DX(dx,x):
 mPlotF.setValue2DX(dx,x)
 mFs=1/dx
 mLen=len(x)
 [mFre,mAmp]=dsp.AmpSpetrum(mLen,mFs,x)
 df=mFs/mLen
 mPlot1F.setValue2DX(df,mAmp)
 return 1

#==Main Window=====================
win= tk.Tk()
sWOld=1920
sHOld=1080
sWidth=win.winfo_screenwidth()
sHeight=win.winfo_screenheight()
wRate=sWidth/sWOld
hRate=sHeight/sHOld
winWidth=int(1100*wRate)
winHeight=int(670*hRate)
x=(sWidth-winWidth)/2;
y=(win.winfo_screenheight()-winHeight)/2
win.geometry("%dx%d+%d+%d" %(winWidth,winHeight,x,y))
win.config(bg="#ddeeee")
win.wm_title('Waveform and Spectrum of MIC')

#==Layout of controls=====================
mLab1=dr.DRLabelX(win,20*wRate,30*hRate,600*wRate,40*hRate,'#003355','#ffffff','Waveform and Spectrum of MIC',20)
mHBut2=dr.DRHButtonGroup(win,690*wRate,30*hRate,200*wRate,36*hRate,'#006688','#ffffff','Record,Stop',2,0)
mRec3=drAudio.DRRecorder(win,900*wRate,30*hRate,120*wRate,36*hRate,'#002244','#ffffff',44100,8192,60)
dr.DRLabelX(win,20*wRate,80*hRate,1000*wRate,550*hRate,'#003355','#ffffff','',20)
mPlotF=dr.DRPlotFast(win,30*wRate,90*hRate,980*wRate,260*hRate,'#003355','#000000','#ffffff','#006677','#ffff00',12,0,0.18,-1,1,0,0)
mPlot1F=dr.DRPlotFast(win,30*wRate,355*hRate,980*wRate,260*hRate,'#003355','#000000','#ffffff','#006677','#ffff00',12,0,6000,0,0.25,0,0)

#=====================================================================
mHBut2.addCallBackSingle(mRec3.setValueSingle)
mRec3.addCallBack2DX(setValue2DX)

#==Main Loop=====================
win.mainloop()

#==End of APPp=====================

