#===This Frame is generated by DRPython ===============================
import sys
import os
import drvi.drviAppendPath as mPath
mPath.appendPythonPath()
#=================================================

import tkinter as tk
import tkinter.messagebox as msgbox
from tkinter import filedialog
import numpy as np
from scipy.fftpack import fft,ifft,fftshift
from scipy import signal
import matplotlib.pyplot as plt
import numpy as np
import drvi.drviDSP as dsp
import drvi.drviControlls as dr
 
#==CallBack Function==============
def setWin(v):
 winT=v; N1=51 
 w=np.ones(N1);
 if winT==0: w=np.ones(N1);
 if winT==1: w=signal.windows.bartlett(N1);
 if winT==2: w=signal.windows.hann(N1);
 if winT==3: w=signal.windows.hamming(N1);
 if winT==4: w=signal.windows.blackman(N1);
 if winT==5: w=signal.windows.flattop(N1);
 mPlotWinWave.setValue2DX(1,w)
 A=fft(w,2048)/(len(w)/2.0)
 freq=np.linspace(-0.5, 0.5,len(A))
 response = 20 * np.log10(np.abs(fftshift(A / abs(A).max())) + 0.000000000000001 )
 mPlotWinAmp.setValue2D(freq, response) 
 return 1

#=================================
def myWorking(v):
 global Fre,winT,winA
 if v<10: winT=v;
 if v>10: Fre=v;     
 Fs1=1024;
 N1=1024 
 dt1=1.0/Fs1; 
 t1=np.arange(N1)*dt1
 w=np.ones(N1)
 x1=0.8*np.sin(2*np.pi*Fre*t1)
 mPlotWave1.setValue2D(t1,x1)
 [mFre,mAmp]=dsp.AmpSpetrum(N1,Fs1,x1)
 mPlotAmp.setValue2D(mFre,mAmp)
 if winT==0: w=np.ones(N1);                 winA=1
 if winT==1: w=signal.windows.bartlett(N1); winA=2
 if winT==2: w=signal.windows.hann(N1);     winA=2
 if winT==3: w=signal.windows.hamming(N1);  winA=1.852
 if winT==4: w=signal.windows.blackman(N1); winA=2.381
 if winT==5: w=signal.windows.flattop(N1);  winA=4.545
 y=x1*w
 mPlotWave2.setValue2D(t1,y)
 [mFre1,mAmp1]=dsp.AmpSpetrum(N1,Fs1,y)
 mAmp1=mAmp1*winA
 mPlotAmp1.setValue2D(mFre1,mAmp1)
 return 1
#==Main Window=====================
win= tk.Tk()
sWOld=1920
sHOld=1080
sWidth=win.winfo_screenwidth()
sHeight=win.winfo_screenheight()
wRate=sWidth/sWOld
hRate=sHeight/sHOld
winWidth=int(1100*wRate)
winHeight=int(670*hRate)
x=(sWidth-winWidth)/2;
y=(win.winfo_screenheight()-winHeight)/2
win.geometry("%dx%d+%d+%d" %(winWidth,winHeight,x,y))
win.config(bg="#ddeeee")
win.wm_title('FFT Spectral Leakage and Windowing')

#==Layout of controls=====================
dr.DRLabelX(win,20*wRate,30*hRate,600*wRate,40*hRate,'#440000','#ffffff','FFT Spectral Leakage and Windowing',20)
mTab=dr.DRTab(win,20*wRate,90*hRate,1040*wRate,540*hRate,'#113344','#ddddff','#ddeeee',2,3)
#Pasge1
mPlotWave1=dr.DRPlotX(mTab.win[0],0*wRate,0*hRate,520*wRate,250*hRate,'','#113344','#000000','#ffffff','#00eeff','#ffff00',0,1,-1,1,0,0)
mPlotWave2=dr.DRPlotX(mTab.win[0],520*wRate,0*hRate,520*wRate,250*hRate,'','#113344','#000000','#ffffff','#00eeff','#ffff00',0,1,-1,1,0,0)
mPlotAmp=dr.DRPlotX(mTab.win[0],0*wRate,250*hRate,520*wRate,250*hRate,'','#113344','#000000','#ffffff','#00eeff','#ffff00',0,500,0,1,0,0)
mPlotAmp1=dr.DRPlotX(mTab.win[0],520*wRate,250*hRate,520*wRate,250*hRate,'','#113344','#000000','#ffffff','#00eeff','#ffff00',0,500,0,1,0,0)
#Page2
mPlotWinWave=dr.DRPlotX(mTab.win[1],0*wRate,0*hRate,520*wRate,500*hRate,'','#113344','#000000','#ffffff','#00eeff','#ffff00',0,0,-1.2,1.2,0,0)
mPlotWinAmp=dr.DRPlotX(mTab.win[1],520*wRate,0*hRate,520*wRate,500*hRate,'','#113344','#000000','#ffffff','#00eeff','#ffff00',0,0,0,0,0,0)
#==============
dr.DRLabelX(win,660*wRate,40*hRate,140*wRate,40*hRate,'#ddeeee','#000000','Frequency',18)
mDigital1=dr.DRDigital(win,800*wRate,40*hRate,120*wRate,40*hRate,'#000000','#00ffaa',45.5,2,22)
mSpin1=dr.DRSpinBox(win,960*wRate,40*hRate,100*wRate,36*hRate,'#ffffff','#000000',45.5,0.1,40,50)
mHBut1=dr.DRHButtonGroup(win,20*wRate,590*hRate,940*wRate,36*hRate,'#113344','#ffffff','Rectangle,Bartlett,Hann,Hamming,BlackMan,FlatTop',6,0)

#==DataStream Binding=====================
mSpin1.addCallBackSingle(mDigital1.setValueSingle)
mSpin1.addCallBackSingle(myWorking)
mHBut1.addCallBackSingle(myWorking)
mHBut1.addCallBackSingle(setWin)
#=============================================
Fre=45
winT=0
winA=1
myWorking(45.5)
setWin(0)
#==Main Loop=====================
win.mainloop()
#==End of APPp=====================

