#===This Frame is generated by DRPython ===============================
import sys
import os
import drvi.drviAppendPath as mPath
mPath.appendPythonPath()
#=================================================

import tkinter as tk
import tkinter.messagebox as msgbox
from tkinter import filedialog
import numpy as np
from scipy.fftpack import fft,ifft
import matplotlib.pyplot as plt
import numpy as np
import drvi.drviDSP as dsp
import drvi.drviControlls as dr

#=========================================

def setValue2D(t,x):
 Fs=1/(t[1]-t[0]);
 N=len(x)
 mPlotWave.setValue2D(t,x)
 M=48
 abin=np.linspace(-1,1,num=M)
 [mHist,bins]=np.histogram(x,bins=abin)
 mPdf=mHist/N
 mPlotPDF.setValue2D(abin[0:M-1],mPdf)
 mCdf=np.cumsum(mPdf)
 mPlotCDF.setValue2D(abin[0:M-1],mCdf)
 return 1 
 
#==Main Window=====================
win= tk.Tk()
sWOld=1920
sHOld=1080
sWidth=win.winfo_screenwidth()
sHeight=win.winfo_screenheight()
wRate=sWidth/sWOld
hRate=sHeight/sHOld
winWidth=int(1100*wRate)
winHeight=int(670*hRate)
x=(sWidth-winWidth)/2;
y=(win.winfo_screenheight()-winHeight)/2
win.geometry("%dx%d+%d+%d" %(winWidth,winHeight,x,y))
win.config(bg="#ddeeee")
win.wm_title('Probability Density and Distribution Curve')


#==Layout of controls=====================
mLab1=dr.DRLabelX(win,20*wRate,30*hRate,600*wRate,40*hRate,'#003355','#ffffff','Probability Density and Distribution Curve',20)
mPlotWave=dr.DRPlotX(win,20*wRate,80*hRate,900*wRate,280*hRate,'','#003355','#000000','#ffffff','#00eeff','#ffff00',0,0.05,-1,1,0,0)
mPlotPDF=dr.DRPlotX(win,20*wRate,350*hRate,450*wRate,280*hRate,'','#003355','#000000','#ffffff','#00eeff','#ffff00',0,0,0,0,0,0)
mPlotCDF=dr.DRPlotX(win,470*wRate,350*hRate,450*wRate,280*hRate,'','#003355','#000000','#ffffff','#00eeff','#ffff00',0,0,0,0,0,0)

mVButType=dr.DRRadioButX(win,940*wRate,100*hRate,120*wRate,140*hRate,'#004466','#000000','#ffffff','#00ccff','#eeee44','Sine,Square,Trangle,Noise',11,4,0)
mKnobA=dr.DRKnob(win,930*wRate,280*hRate,130*wRate,130*hRate,'#004466','#222222','#aaaaaa','0,1',0,1,0.5)
mKnobFre=dr.DRKnob(win,930*wRate,400*hRate,130*wRate,130*hRate,'#004466','#222222','#aaaaaa','1,1000',1,1000,50)

mType=0; Fs=44100; N=8192; A=0.6; Fre=100; Pha=0
mSignal=dsp.DRGenerator(mType,Fs,N,A,Fre,Pha)

#==DataStream Binding=====================
mSignal.addCallBackValue2D(setValue2D)
mVButType.addCallBackSingle(mSignal.setSignalType)
mKnobA.addCallBackSingle(mSignal.setSignalAmp)
mKnobFre.addCallBackSingle(mSignal.setSignalFre) 
    
#==Main Loop=====================
win.mainloop()

#==End of APPp=====================

